# Generated by Django 3.2.24 on 2024-03-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('project_year', models.CharField(max_length=4)),
                ('size', models.CharField(max_length=20)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/cover_images/')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.location')),
                ('typology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.typology')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/process_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_images', to='projects.project')),
            ],
        ),
    ]
