# Generated by Django 3.2.24 on 2024-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_big',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
