# Generated by Django 5.2.2 on 2026-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_assign_project_disciplines'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=12)),
                ('email_error', models.TextField(blank=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField(blank=True, max_length=500)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seeking_internship', models.BooleanField(default=False)),
                ('portfolio_link', models.URLField(blank=True, max_length=500)),
                ('portfolio_filename', models.CharField(blank=True, max_length=255)),
                ('portfolio_content_type', models.CharField(blank=True, max_length=100)),
                ('portfolio_data', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=12)),
                ('email_error', models.TextField(blank=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('project_type', models.CharField(choices=[('architecture', 'Architecture'), ('interiors', 'Interior design'), ('architecture-interiors', 'Architecture + interiors'), ('landscape', 'Landscape'), ('other', 'Something else')], max_length=30)),
                ('project_location', models.CharField(blank=True, max_length=150)),
                ('preferred_call_time', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(max_length=3000)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
