# Generated by Django 3.2.24 on 2025-12-21 07:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('total_read_time', models.PositiveIntegerField(blank=True, help_text='Estimated read time in minutes', null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/cover_images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
